// angular-project/src/app/components/timeline-grid/timeline-grid.component.ts
import {
  Component,
  Input,
  OnChanges,
  SimpleChanges,
  ElementRef,
  ViewChild,
  AfterViewInit,
  ChangeDetectionStrategy,
} from '@angular/core';
import { NgFor, NgIf, NgStyle } from '@angular/common';
import {
  WorkCenterDocument,
  WorkOrderDocument,
  ZoomLevel,
} from '../../models/work-order.model';
import {
  getVisibleRange,
  getPixelsPerDay,
  dateToPixel,
  dateRangeToWidth,
  daysBetween,
  generateHeaderDates,
  pixelToDate,
  todayStr,
} from '../../utils/date.utils';
import { WorkOrderBarComponent } from '../work-order-bar/work-order-bar.component';
import { WorkOrderService } from '../../services/work-order.service';

@Component({
  selector: 'app-timeline-grid',
  standalone: true,
  imports: [NgFor, NgIf, NgStyle, WorkOrderBarComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="timeline" #scrollContainer (scroll)="onScroll()">
      <div class="timeline__canvas" [ngStyle]="{ width: totalWidth + 'px' }">
        <!-- Header -->
        <div class="timeline__header">
          <div
            *ngFor="let col of headerDates; trackBy: trackByLabel"
            class="timeline__header-cell"
            [class.timeline__header-cell--weekend]="col.isWeekend"
            [ngStyle]="{ width: columnWidth + 'px' }"
          >
            {{ col.label }}
          </div>
        </div>

        <!-- Rows -->
        <div class="timeline__body">
          <div
            *ngFor="let wc of workCenters; trackBy: trackByDocId"
            class="timeline__row"
            (click)="onRowClick($event, wc.docId)"
          >
            <!-- Grid columns -->
            <div
              *ngFor="let col of headerDates; trackBy: trackByLabel"
              class="timeline__cell"
              [class.timeline__cell--weekend]="col.isWeekend"
              [ngStyle]="{ width: columnWidth + 'px' }"
            ></div>

            <!-- Work order bars -->
            <app-work-order-bar
              *ngFor="let wo of getOrdersForWC(wc.docId); trackBy: trackByDocId"
              [order]="wo"
              [left]="getBarLeft(wo)"
              [width]="getBarWidth(wo)"
            />
          </div>

          <!-- Today indicator -->
          <div
            *ngIf="todayPixel >= 0"
            class="timeline__today"
            [ngStyle]="{ left: todayPixel + 'px' }"
          >
            <div class="timeline__today-dot"></div>
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrl: './timeline-grid.component.scss',
})
export class TimelineGridComponent implements OnChanges, AfterViewInit {
  @Input() workCenters: WorkCenterDocument[] = [];
  @Input() workOrders: WorkOrderDocument[] = [];
  @Input() zoom: ZoomLevel = 'day';

  @ViewChild('scrollContainer') scrollContainer!: ElementRef<HTMLDivElement>;

  headerDates: { date: Date; label: string; isWeekend: boolean }[] = [];
  totalWidth = 0;
  columnWidth = 0;
  todayPixel = 0;

  private visibleStart!: Date;
  private visibleEnd!: Date;
  private pixelsPerDay = 60;
  private needsCenter = true;

  constructor(private service: WorkOrderService) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['zoom'] || changes['workOrders'] || changes['workCenters']) {
      this.recalculate();
      this.needsCenter = true;
    }
  }

  ngAfterViewInit(): void {
    if (this.needsCenter) {
      this.centerOnToday();
      this.needsCenter = false;
    }
  }

  private recalculate(): void {
    const range = getVisibleRange(this.zoom);
    this.visibleStart = range.start;
    this.visibleEnd = range.end;
    this.pixelsPerDay = getPixelsPerDay(this.zoom);

    this.headerDates = generateHeaderDates(this.visibleStart, this.visibleEnd, this.zoom);

    // Column width depends on zoom
    switch (this.zoom) {
      case 'day':   this.columnWidth = this.pixelsPerDay; break;
      case 'week':  this.columnWidth = this.pixelsPerDay * 7; break;
      case 'month': this.columnWidth = this.pixelsPerDay * 30; break;
    }

    this.totalWidth = this.headerDates.length * this.columnWidth;
    this.todayPixel = dateToPixel(todayStr(), this.visibleStart, this.pixelsPerDay);

    // Center after the view updates
    setTimeout(() => this.centerOnToday());
  }

  private centerOnToday(): void {
    if (!this.scrollContainer) return;
    const el = this.scrollContainer.nativeElement;
    const scrollTo = this.todayPixel - el.clientWidth / 2;
    el.scrollLeft = Math.max(0, scrollTo);
  }

  getOrdersForWC(wcId: string): WorkOrderDocument[] {
    return this.workOrders.filter((wo) => wo.data.workCenterId === wcId);
  }

  getBarLeft(wo: WorkOrderDocument): number {
    return dateToPixel(wo.data.startDate, this.visibleStart, this.pixelsPerDay);
  }

  getBarWidth(wo: WorkOrderDocument): number {
    return dateRangeToWidth(wo.data.startDate, wo.data.endDate, this.pixelsPerDay);
  }

  onRowClick(event: MouseEvent, workCenterId: string): void {
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    const scrollLeft = this.scrollContainer.nativeElement.scrollLeft;
    const clickX = event.clientX - rect.left + scrollLeft;
    const clickedDate = pixelToDate(clickX, this.visibleStart, this.pixelsPerDay);
    this.service.openCreatePanel(workCenterId, clickedDate);
  }

  onScroll(): void {
    // Could be used for virtual scrolling in the future
  }

  trackByDocId(_: number, item: { docId: string }): string {
    return item.docId;
  }

  trackByLabel(_: number, item: { label: string }): string {
    return item.label;
  }
}

// src/components/timeline/TimelineGrid.tsx
import React, { useRef, useMemo, useEffect } from 'react';
import { WorkCenterDocument, WorkOrderDocument, ZoomLevel } from '@/types/workOrder';
import {
  getVisibleRange,
  getPixelsPerDay,
  dateToPixel,
  dateRangeToWidth,
  pixelToDate,
  generateHeaderDates,
  daysBetween,
  todayStr,
} from '@/utils/dateUtils';
import WorkOrderBar from './WorkOrderBar';
import { ROW_HEIGHT } from './WorkCenterPanel';

interface TimelineGridProps {
  workCenters: WorkCenterDocument[];
  workOrders: WorkOrderDocument[];
  zoom: ZoomLevel;
  onClickEmpty: (workCenterId: string, date: string) => void;
  onEditOrder: (order: WorkOrderDocument) => void;
  onDeleteOrder: (docId: string) => void;
  scrollRef: React.RefObject<HTMLDivElement>;
}

const HEADER_HEIGHT = 56;

const TimelineGrid: React.FC<TimelineGridProps> = ({
  workCenters,
  workOrders,
  zoom,
  onClickEmpty,
  onEditOrder,
  onDeleteOrder,
  scrollRef,
}) => {
  const { start: visibleStart, end: visibleEnd } = useMemo(() => getVisibleRange(zoom), [zoom]);
  const pixelsPerDay = useMemo(() => getPixelsPerDay(zoom), [zoom]);
  const totalDays = useMemo(() => daysBetween(visibleStart, visibleEnd), [visibleStart, visibleEnd]);
  const totalWidth = totalDays * pixelsPerDay;

  const headerDates = useMemo(
    () => generateHeaderDates(visibleStart, visibleEnd, zoom),
    [visibleStart, visibleEnd, zoom]
  );

  // Today indicator position
  const todayLeft = useMemo(
    () => dateToPixel(todayStr(), visibleStart, pixelsPerDay),
    [visibleStart, pixelsPerDay]
  );

  // Center on today when zoom changes
  useEffect(() => {
    if (scrollRef.current) {
      const containerWidth = scrollRef.current.clientWidth;
      scrollRef.current.scrollLeft = todayLeft - containerWidth / 2;
    }
  }, [zoom, todayLeft, scrollRef]);

  /**
   * Handle click on empty timeline area to create a new work order.
   */
  const handleRowClick = (workCenterId: string, e: React.MouseEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const scrollLeft = scrollRef.current?.scrollLeft || 0;
    // Calculate pixel offset relative to the full timeline
    const pixelOffset = e.clientX - rect.left + scrollLeft;
    const clickedDate = pixelToDate(pixelOffset, visibleStart, pixelsPerDay);
    onClickEmpty(workCenterId, clickedDate);
  };

  return (
    <div className="flex-1 overflow-x-auto overflow-y-hidden" ref={scrollRef}>
      <div style={{ width: totalWidth, minWidth: '100%' }}>
        {/* Header row */}
        <div
          className="sticky top-0 z-20 border-b border-border bg-timeline-header flex"
          style={{ height: HEADER_HEIGHT }}
        >
          {headerDates.map((hd, i) => {
            const left = dateToPixel(
              hd.date.toISOString().split('T')[0],
              visibleStart,
              pixelsPerDay
            );
            const cellWidth = zoom === 'day' ? pixelsPerDay : zoom === 'week' ? pixelsPerDay * 7 : pixelsPerDay * 30;

            return (
              <div
                key={i}
                className={`flex-shrink-0 flex items-end pb-2 px-1 border-r border-border/50
                           ${hd.isWeekend ? 'bg-timeline-weekend' : ''}`}
                style={{ width: cellWidth }}
              >
                <span
                  className={`text-[10px] font-medium tracking-wide
                             ${hd.isWeekend ? 'text-muted-foreground/60' : 'text-muted-foreground'}`}
                >
                  {hd.label}
                </span>
              </div>
            );
          })}
        </div>

        {/* Timeline rows */}
        <div className="relative">
          {/* Today indicator */}
          <div
            className="absolute top-0 bottom-0 z-10 pointer-events-none"
            style={{ left: todayLeft }}
          >
            <div className="w-px h-full bg-timeline-today opacity-60" />
            <div
              className="absolute -top-1 left-1/2 -translate-x-1/2
                         w-2 h-2 rounded-full bg-timeline-today"
            />
          </div>

          {workCenters.map((wc) => {
            const orders = workOrders.filter((wo) => wo.data.workCenterId === wc.docId);

            return (
              <div
                key={wc.docId}
                className="relative border-b border-border hover:bg-primary/[0.02] transition-colors cursor-pointer"
                style={{ height: ROW_HEIGHT }}
                onClick={(e) => handleRowClick(wc.docId, e)}
              >
                {/* Grid lines */}
                {zoom === 'day' &&
                  headerDates.map((hd, i) => {
                    const cellLeft = dateToPixel(
                      hd.date.toISOString().split('T')[0],
                      visibleStart,
                      pixelsPerDay
                    );
                    return (
                      <div
                        key={i}
                        className={`absolute top-0 bottom-0 border-r border-border/30
                                   ${hd.isWeekend ? 'bg-muted/30' : ''}`}
                        style={{ left: cellLeft, width: pixelsPerDay }}
                      />
                    );
                  })}

                {/* Work order bars */}
                {orders.map((order) => {
                  const left = dateToPixel(order.data.startDate, visibleStart, pixelsPerDay);
                  const width = dateRangeToWidth(order.data.startDate, order.data.endDate, pixelsPerDay);

                  return (
                    <WorkOrderBar
                      key={order.docId}
                      order={order}
                      left={left}
                      width={width}
                      onEdit={onEditOrder}
                      onDelete={onDeleteOrder}
                    />
                  );
                })}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default TimelineGrid;
export { HEADER_HEIGHT };
